version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - qa_data:/app/backend/qa_files
    restart: unless-stopped
    networks:
      - qa_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - qa_network
    environment:
      - VITE_API_URL=http://backend:8000

volumes:
  qa_data:

networks:
  qa_network:
    driver: bridge 